### ISSUE TITLE
Please break this repo out into individual repos.

### ISSUE THREAD

**Issue by avaidyam** [PurdueIEEEComputerSociety/Csociety-Projects#1]
That is all. //cc @mattmolo

**Comment by exponentialbit1024** [comment]
when every thing has substantial amount of work, and effort to be really pursued it will be, again if you wish to carry forward any/all of them, by all means, go for it.

**Comment by mattmolo** [comment]
@avaidyam This is _CSociety-Projects_
![You have no power here](https://media.giphy.com/media/RX3vhj311HKLe/giphy.gif)

**Comment by avaidyam** [comment]
Fair enough. Also @exponentialbit1024 Leyden is not coming up until Monday. Not worth my time.

**Comment by exponentialbit1024** [comment]
dw I've got it covered and it'll be up tomorrow
